# sample hyprlock.conf
# for more configuration options, refer https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock
#
# rendered text in all widgets supports pango markup (e.g. <b> or <i> tags)
# ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#general-remarks
#
# shortcuts to clear password buffer: ESC, Ctrl+U, Ctrl+Backspace
#
# you can get started by copying this config to ~/.config/hypr/hyprlock.conf
#








$font = Monospace

general {
    hide_cursor = false
}

# uncomment to enable fingerprint authentication
# auth {
#     fingerprint {
#         enabled = true
#         ready_message = Scan fingerprint to unlock
#         present_message = Scanning...
#         retry_delay = 250 # in milliseconds
#     }
# }

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}



background {
  monitor=DP-1
  blur_passes=2
  blur_size=3
  noise=0.011700
  path=/home/redstar/Documents/Archive/Wallpapers/1287814.png
}


# Image ontop ontop of the input field
#image {
#  monitor=DP-1
#  halign=center
#  path=/home/redstar/Documents/Archive/Wallpapers/Imperial Eagle.jpg
#  position=0, 50
#  valign=center
#}

input-field {
  monitor=DP-1
  size=200,50

  dots_center=true
  dots_size=0.200000
  dots_spacing=0.350000

  fade_on_empty=false

  font_color=rgba(24, 24, 24, 0.96)
  halign=center
  hide_input=false


  inner_color = rgba(241, 241, 241, 0.76) # no fill
  outer_color = rgba(255, 174, 43, 0.87) rgba(255, 88, 27, 0.92) 45deg
  check_color = rgba(179, 57, 255, 0.97) rgba(255, 24, 24, 0.92) 120deg
  fail_color = rgba(255, 32, 181, 0.95) rgba(255, 0, 0, 0.94) 40deg

  outline_thickness = 2
  placeholder_text = Input Password...
  position = 0, -100
  rounding = -1

  halign = center
  valign=center
}


# Time
label {
  monitor=DP-1
  color=rgba(242, 243, 244, 0.75)
  font_family=JetBrains Mono
  font_size=95
  halign=center
  position=0, 300
  text=$TIME
  valign=center
}

# Date
label {
  monitor=DP-1
  color=rgba(242, 243, 244, 0.75)
  font_family=JetBrains Mono
  font_size=22
  halign=center
  position=0, 200
  text=cmd[update:1000] echo $(date +"%A, %B %d")
  valign=center
}





#input-field {
#    monitor =
#    size = 20%, 5%
#    outline_thickness = 3
#    inner_color = rgba(0, 0, 0, 0.0) # no fill
#
#    outer_color = rgba(33ccffee) rgba(00ff99ee) 45deg
#    check_color = rgba(00ff99ee) rgba(ff6633ee) 120deg
#    fail_color = rgba(ff6633ee) rgba(ff0066ee) 40deg
#
#    font_color = rgb(143, 143, 143)
#    fade_on_empty = false
#    rounding = 15
#
#    font_family = $font
#    placeholder_text = Input password...
#    fail_text = $PAMFAIL
#
#    # uncomment to use a letter instead of a dot to indicate the typed password
#    # dots_text_format = *
#    # dots_size = 0.4
#    dots_spacing = 0.3
#
#    # uncomment to use an input indicator that does not show the password length (similar to swaylock's input indicator)
#    # hide_input = true
#
#    position = 0, -20
#    halign = center
#    valign = center
#}
