monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "~alsa_output.usb-Apple__Inc._USB-C_to_3.5mm.*"
      }
    ]
    actions = {
      update-props = {
        node.name = "alsa_output.apple-usb-headphone"
      }
    }
  }
]